### ISSUE TITLE
[La data visualisation pour la data science (et les data scientists)] Christophe Bontemps

### ISSUE THREAD

**Issue by XtopheB** [TlseDataScience/meetup-cfp#3]
## Le speaker
Christophe Bontemps, Ingénieur de recherche (économétrie) à _Toulouse School of Economics_ (INRA)
* Twitter handle: [@Xtophe_Bontemps](https://twitter.com/Xtophe_Bontemps)

## Sujet de votre conférence
Il s'agit d'une sorte de leçon sur la visualisation de données (dataviz) pour les data scientists. J'apporterai quelques éclairages sur les buts et objectifs de la visualisation et montrerai sur des exemples comment la data visualisation permet de _voir ce que l'on ne pensait pas voir_".  

> "Voir ce que l'on ne pensait pas voir"

## Description de votre conférence
Le métier de _data scientist_ comporte bien des facettes, mais repose avant tout sur une bonne appréhension des données, quelles soient brutes ou issues de traitements statistiques. La construction d'outils de visualisation de ces données est alors une étape  importante pour tester les premières caractéristiques de ces données, les premières relations, les premiers patterns, ... Je vous propose un tour d'horizon pratique des méthodes et des outils ( statiques ou dynamiques) qui permettent de visualiser efficacement vos données, puis de les présenter. Il faudra pour cela suivre quelques règles pour mieux s'en affranchir.    

## Informations diverses
* Thématique, Labels : data science, dataviz
* Niveau de difficulté (débutant|avancé|confirmé) : Tous,
* Durée (quickie 15-30min, conférence >1h) : conférence >1h
* Format (slides, live-coding, les deux):  Slides + démos live (!)+ quizzes live (!)
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):  pas avant le premier trimestre 2018

**Comment by vfdev-5** [comment]
Est-ce que l'utilisation de l'outil de [Google PAIR - facets](https://opensource.googleblog.com/2017/07/facets-open-source-visualization-tool.html) sera abordé dans cette conférence ? 
Personellement, j'ai fait quelques tests de l'outil sur certains datasets d'images et je voudrais savoir si on peut avancer plus avec l'outil ou utiliser autre chose pour le même but.

**Comment by XtopheB** [comment]
Bonsoir,
Le projet d'intervention que j'ai déposé n'est pas du tout figé (et je ne sais pas d'ailleurs s'il verra le jour), mais je n'aborderai probablement pas la pratique spécifique d'un outil, mais plutôt la question des pratiques  de visualisation en data science en illustrant sur des exemples. Cela peut-être un bon exemple de confusion matrix par exemple...
Merci en tout cas pour l'intérêt que vous portez à ce projet.
Cordialement,
Christophe

De : vfdev [mailto:notifications@github.com]
Envoyé : mardi 3 octobre 2017 23:15
À : TlseDataScience/meetup-cfp
Cc : Christophe Bontemps; Author
Objet : Re: [TlseDataScience/meetup-cfp] [La data visualisation pour la data science (et les data scientists)] Christophe Bontemps (#3)


Est-ce que l'utilisation de l'outil de Google PAIR - facets<https://opensource.googleblog.com/2017/07/facets-open-source-visualization-tool.html> sera abordé dans cette conférence ?
Personellement, j'ai fait quelques tests de l'outil sur certains datasets d'images et je voudrais savoir si on peut avancer plus avec l'outil ou utiliser autre chose pour le même but.

-

**Comment by vfdev-5** [comment]
Merci pour la réponse, Christophe, j’espère que ce CFP verra bien le jour ! 
Si le contenu de la présentation change vers quelques exemples concrets d'utilisation de certains outils, je serais ravi aussi d'intervenir avec un cas d'utilisation de l'outil "Google Facets" dans l'environnement Jupyter Notebook.
Cordialement,
Victor
