### ISSUE TITLE
[BrainChip: Ce que les réseaux à spike peuvent amener au deep learning] Sébatien Crouzet

### ISSUE THREAD

**Issue by rchevalier-brainchip** [TlseDataScience/meetup-cfp#32]
## Le speaker
[Sébastien Crouzet](https://github.com/scrouzet) -- R&D Engineer chez [Brainchip](https://doc.brainchipinc.com/)

## Sujet de votre conférence
BrainChip: Ce que les réseaux à spike peuvent amener au deep learning

## Description de votre conférence
S'inspirer de la nature pour améliorer la technologie est toujours une idée séduisante, le risque étant de faire de la `bio-mimicry`, c'est à dire de copier des artefacts de la nature qui ne sont pas essentiels pour la tache visée (des avions qui battent des ailes) . Qu'en est-il du deep learning ? Peut-on s'inspirer du cerveau pour l'améliorer ? 
Chez Brainchip, nous utilisons certaines caractéristiques des réseaux de neurones à spike (SNN) afin de rendre plus performant le deep learning et ses applications, principalement en ce qui concerne leur consommation énergétique.
Dans cette présentation, nous expliquerons brièvement ce que sont les réseaux de neurones à spike, avant d'exposer le travail de BrainChip qui s'en inspire pour créer une puce permettant d'appliquer le deep learning `on the edge`. 

## Informations diverses
* Thématique, Labels : deep learning, low-power, event-based, quantization, edge learning, mobile, IoT
* Niveau de difficulté (débutant|avancé|confirmé) : avancé
* Durée (quickie 15-30min, conférence >1h) : 1h
* Format (slides, live-coding, les deux):  les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dès que possible
* Support en ligne: https://doc.brainchipinc.com/examples/index.html

**Comment by fchouteau** [comment]
Bonjour Sébastien,

Merci pour ton CFP (avec un peu de retard),

Serais-tu disponible en Octobre (semaine 44, entre le 26 et le 30) pour présenter ton sujet ? 

Si oui, pourrais-tu nous écrire à core-team at tlse-data-science dot fr afin que nous puissons régler les derniers détails ?

**Comment by scrouzet** [comment]
Bonjour,

Merci pour le retour. Nous avions déposé cette proposition en février, dans un contexte bien différent, avec l'idée de faire une présentation à la fois théorique/historique sur le deep learning et les réseaux à spike, et un atelier intéractif rapide basé sur nos tutoriaux en ligne. Au vu du délai et du contexte actuel (présentation en remote), nous serions plutôt favorable à remettre cela en route dans quelques mois, en espérant que la situation se relaxe d'ici là concernant ce type d'évènement.

Sébastien

**Comment by fchouteau** [comment]
Bonjour Sébastien,

Merci pour la réponse,

On se recontacte donc en 2021 lorsque l'horizon se dégagera :crossed_fingers: 

L'équipe TDS
