### ISSUE TITLE
Evaluation of Conversational Agents for Aerospace Domain

### ISSUE THREAD

**Issue by ggdupont** [TlseDataScience/meetup-cfp#33]
## Le speaker
Gérard DUPONT, senior AI researcher at AIRBUS

* Twitter handle: @ggdupont

## Sujet de votre conférence
Evaluation of Conversational Agents for Aerospace Domain

## Description de votre conférence
What if we put a chatbot in a cockpit?

From the original research idea to the actual live experiments in a cockpit... simulator since it's far from being ready to flight. The objective of the talk will be to show the trajectory of this research topic, from funding hypothesis to actual prototyping and results. We will dive in the technical details of the system proposed and how state-of-the)art approaches have been adapted to a real industrial scenario and validated with humans.

The presentation will mostly rely on published material in CIRCLE2020 conference which comes after a 2 years efforts to support pilots and their access to cockpit documentation. 

## Informations diverses
* Thématique, Labels : NLP, information retrieval, question answering, conversational agent, aeronautics, human experiments
* Niveau de difficulté (débutant|avancé|confirmé) : avancé
* Durée (quickie 15-30min, conférence >1h) : 1h
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): de préférence pas le Mercredi ni le Vendredi.

**Comment by fchouteau** [comment]
Meetup effectué le 30/09/2020, merci @ggdupont pour cette excellente présentation !
