### ISSUE TITLE
[Application of Computer Vision Deep Learning techniques in domain of GPS signals] Evgenii Munin 

### ISSUE THREAD

**Issue by EvgeniiMunin** [TlseDataScience/meetup-cfp#34]
## Le speaker
Evgenii Munin -- PhD Candidate at ENAC
https://www.linkedin.com/in/evgenii-munin-01932a143/

## Sujet de votre conférence
Application of Computer Vision Deep Learning techniques in domain of GPS signals

## Description de votre conférence
Les signaux GPS sont souvent soumis aux différents types d'événements provoquants la degradation de positionnement. Dans beaucoup des cas ce type d'erreur est du à la présence des obstacles (dites de canion urban: bâtiment, voitures etc.). Ces obstacles par reflection génerent des signaux multiples qui peuvent biaiser le positionnement du récepteur GPS.  

Dans cette présentation nous expliqueront une façons à détecter les erreurs liées aux trajets multiples en utilisant l'approche de Computer Vision. On va decrire le detecteur qui intervient au niveau de récepteur GPS et travail avec le signal brute. Puis on parlera de la question de la possibilité de faire tourner ce type détecteur sur une module de basse consommation d'énergie en utilisant I'Intel Neural Compute Stick VPU.

## Informations diverses
* Thématique, Labels : deep learning, GPS, VPU, Image
* Niveau de difficulté (débutant|avancé|confirmé) : avancé (mais sinon c'est pas grâve, je vais expliquer des choses de manière simple)
* Durée (quickie 15-30min, conférence >1h) : quickie 20-30min (+ demo 5 min)
* Format (slides, live-coding, les deux): slides + pétit demo
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): Novembre- Decembre 2020
* Support en ligne: papier + présentation conf (pour le meetup ça va être beaucoup plus simple) https://drive.google.com/drive/folders/1v5C7gg6bxaG0oXo9-MSN8XUhd4g6JXfq?usp=sharing

**Comment by fchouteau** [comment]
Le meetup a eu lieu le 25/11/2020
