### ISSUE TITLE
[adacraft, du "block coding" pour découvrir et jouer avec l'IA] Nicolas Decoster

### ISSUE THREAD

**Issue by ogadaki** [TlseDataScience/meetup-cfp#35]
## Le speaker
Nicolas Decoster, développeur

* Twitter handle: @ogadaki

## Sujet de votre conférence
adacraft, du "block coding" pour découvrir et jouer avec l'IA

## Description de votre conférence

Comment rendre l'IA plus accessible pour permettre à quiconque de la manipuler pour mieux comprendre ce qu'il y a derrière ou tout simplement pour s'amuser avec elle ?

Ces derniers temps de nombreux algos et modèles ont fait leur apparition dans le navigateur, et il y a de plus en plus d'outils en ligne permettant de mieux comprendre et de jouer avec ces concepts. Pour n'en citer qu'un, [Teachable Machine](https://teachablemachine.withgoogle.com/) permet d'entraîner très facilement des modèles de reconnaissance d'images, de sons ou de pose. Pour ceux qui ne connaissent pas le Machine Learning, l'effet "Waou !" est garanti. Mais cet outil se limite à la partie apprentissage et il faut mettre les mains dans le cambouis pour créer quelque chose avec le modèle, ce qui rebute les "non-experts" en programmation. Quid de rendre également plus accessible la création de mini projets qui utilisent ces modèles ? Réponse : utiliser la programmation par bloc à la [Scratch](https://scratch.mit.edu/) !

Dans ce talk, je vous présenterai [adacraft](https://adacraft.org/), un fork modifié de Scratch pour ouvrir la créativité et qui embarque des extensions dédiées à l'IA. Je vous parlerez également de mon expérience à [la Compagnie du Code](https://www.lacompagnieducode.org/) dans l'animation d'ateliers avec des jeunes pour découvrir l'IA avec ce type d'outils.

## Informations diverses
* Thématique, Labels : vulgarisation, non-experts, programmation visuelle, IA
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (quickie 15-30min, conférence >1h) :  conférence
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):

**Comment by vfdev-5** [comment]
La présentation a eu lieu en décembre.
