### ISSUE TITLE
3D reconstruction using NeRF - Alberto CEBALLOS

### ISSUE THREAD

**Issue by ceballos-alberto** [TlseDataScience/meetup-cfp#42]
## Le speaker

Alberto CEBALLOS

## Sujet de votre conférence

3D reconstruction of critical infrastructures using Neural Radiance Fields

## Description de votre conférence

Since the introduction of Neural Radiance Fields in 2020, there has been a growing interest in this new field of Deep Learning. NeRF is a completely new approach to the old problem of novel view synthesis and 3D reconstruction that could potentially replace traditional photogrammetry. In this talk we will present the topic and show how Alteia is using this technology to inspect electrical infrastructures. The conference will be in english. 

## Informations diverses

* Thématique, Labels : Neural Radiance Fields, 3D reconstruction, Deep Learning. 
* Niveau de difficulté : débutant.
* Durée : 30min.
* Format : slides.
* Dispo : à partir de septembre.

**Comment by fchouteau** [comment]
Meetup effectué en février 2023
