### ISSUE TITLE
[DEEP LEARNING APPLICATIONS TO 3D DATA] Nicola Luminari

### ISSUE THREAD

**Issue by appanacca** [TlseDataScience/meetup-cfp#43]
## Le speaker
Nicola Luminari

* Twitter handle: @appanacca

## Sujet de votre conférence
Deep Learning Applications to 3D data

## Description de votre conférence
Nous allons explorer les dernières avancées dans deux domaines passionnants: la reconstruction de scènes 3D avec Nerf et la segmentation sémantique des point clouds.

La reconstruction de scènes 3D est un domaine en constante évolution qui permet de créer des modèles 3D précis à partir de données 2D. Avec Nerf, nous pouvons maintenant utiliser des réseaux de neurones pour reconstruire des scènes 3D.

La segmentation sémantique des point clouds est également un domaine en évolution rapide. Il s'agit de classer les points d'un nuage de points en différentes catégories, comme le sol, les bâtiments ou les arbres. Les réseaux de neurones profonds permettent de réaliser cette tâche de manière plus précise et plus rapide qu'auparavant.

Au cours de cette conférence, nous allons discuter des dernières avancées dans ces deux domaines et explorer les nouvelles opportunités qu'ils offrent pour les applications industrielles et les défis à relever pour les chercheurs. 

## Informations diverses
* Thématique, Labels : deep learning, computer vision, nerf, point clouds
* Niveau de difficulté (débutant|avancé|confirmé) : débutant / intermediaire
* Durée (quickie 15-30min, conférence >1h) : 2 * 40 min
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dés que possible

**Comment by fchouteau** [comment]
Meetup effectué en février 2023
