### ISSUE TITLE
[Introduction à la régression symbolique] Max Halford

### ISSUE THREAD

**Issue by MaxHalford** [TlseDataScience/meetup-cfp#6]
## Le speaker

Max Halford, doctorant à l'IMT et à l'IRIT 

* Twitter handle: /

## Sujet de votre conférence

Introduction à la régression symbolique

## Description de votre conférence

Les algorithmes évolutionnistes datant des années 80 ont récemment pris de l'essor. La [régression symbolique](https://www.wikiwand.com/en/Symbolic_regression), branche de la programmation génétique, est une approche innovante qui mérite d'être connue. Elle commence à gagner en popularité sur Kaggle où elle est notamment utilisé pour faire du stacking ([[1]](https://www.kaggle.com/scirpus/genetic-programming-lb-0-88/), [[2]](https://www.kaggle.com/scirpus/big-gp/)). Lors de cet exposé je veux vous introduire à différents concepts et ajouter un outil à votre panoplie de data scientist. Entre autre je prendrai quelques minutes pour vous introduire au package Python que je suis en train de développer.

## Informations diverses

* Thématique, Labels : Machine learning, programmation génétique, algorithmes génétiques, Python, Golang
* Niveau de difficulté (débutant|avancé|confirmé) : Confirmé
* Durée (quickie 15-30min, conférence >1h) :  Quickie
* Format (slides, live-coding, les deux): Slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): Pour décembre

**Comment by vfdev-5** [comment]
@MaxHalford Merci d'avoir proposé ce sujet, ça a l'air intéressant. Peux-tu mettre quelques liens utiles (kernels sur Kaggle, par exemple, comme tu en parles) sur le sujet, stp.

**Comment by MaxHalford** [comment]
@vfdev-5 j'ai mis à jour le post avec quelques liens! N'hésitez pas à me dire s'il en faut un peu plus.

**Comment by XtopheB** [comment]
Je ne sais pas si cette proposition d'intervention est toujours d'actualité, mais je serai assez intéressé de voir ces méthodes en pratique. J'ai un peu joué dans ma jeunesse avec les algorithmes évolutionnistes en optimisation ( (algorithmes génétiques, simulated annealing, taboo search, etc..)  et utilise maintenant des méthodes non paramétriques de régression - qui sont elles aussi data-driven- et suis du coup intrigué par la regression symbolique dont je ne connais pas grand-chose.

**Comment by MaxHalford** [comment]
J'aurais bien aimé parlé en juin mais ca ne colle pas avec mes obligations... Je me mettrai à disposition à la prochaine occasion avec grand plaisir. J'ai eu un peu de tant de travailler sur ma librairie qui s'appelle [XGP](https://github.com/MaxHalford/xgp); j'ai aussi fait des [bindings en Python](https://github.com/MaxHalford/xgp-python).

**Comment by MaxHalford** [comment]
Je ferme ce sujet, ayant proposé un autre qui me semble tout aussi pertinent, sinon plus!
